services:
  - type: web
    name: utility-tools-hub
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: REMOVEBG_API_KEY
        sync: false
